### PR TITLE
fix: 3d_columns example

### PR DESCRIPTION
**Pull request by GuimilXD**
Using:
bevy = "0.10.1"
hexx = "0.5.3"

Rust version 1.67.0

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by ManevilleF** [comment]
The `.collect()` is required to get a `Vec`. Does it compile on your computer ?

Screenshot 2023-05-01 at 18 21 50

**Comment by GuimilXD** [comment]
> The `.collect()` is required to get a `Vec`. Does it compile on your computer ?
> 
> Screenshot 2023-05-01 at 18 21 50

Yes, it only compiles when I remove `.collect()`

**Comment by alice-i-cecile** [comment]
Oh, I bet this is a `main` vs `latest` situation again. I bet the API has changed since the last release.

**Comment by GuimilXD** [comment]
Oh, Gotcha! I thought it was the other way around, thought I was updating the code to run on the latest API version. My bad!

**Comment by ManevilleF** [comment]
Yes, I managed to get `Hex::ring` to return an iterator instead of a Vec in #68 

Theses changes are in the unreleased section of the changelog, the 0.6.0 should release soon

**Pull request closed without merging**
