### PR TITLE
Fixes ring offset

### LINKED ISSUE #22: `Hex::ring` returns incorrect results
The radius is correct, but the values are offset from the center, in a way that seems to vary with the absolute position of the center.

### PR DESCRIPTION
**Pull request by ManevilleF**
> Closes #22

### CODE REVIEW

**Comment by ManevilleF** [comment]
@alice-i-cecile Could you check if your use case works with this fix ?

I'm not very happy with this fix, I'm going to try and improve the code for rings

**Comment by alice-i-cecile** [comment]
Sounds good, I'll try out the git dependency.

**Comment by alice-i-cecile** [comment]
image


Fixes the problem beautifully!

**Comment by alice-i-cecile** [comment]
Are you planning to release 0.3 shortly? Trying to decide whether or not to use the git branch :)

**Review by alice-i-cecile — APPROVED** [review]
Approving as this fixes the problem :)

**Comment by ManevilleF** [comment]
> Are you planning to release 0.3 shortly? Trying to decide whether or not to use the git branch :)

I would say next week ? I think the division issue should be resolved for 0.3

**Pull request merged**
